/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odyssey;

import XMLconvert.JAXBObjectToXml;
import XMLconvert.User;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.io.StringReader;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.*;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Attr;
import org.xml.sax.InputSource;
import org.xml.sax.SAXException;

/**
 * @author josek
 */
public class SingIn extends javax.swing.JFrame {

    Socket SingInCliente;
    int puerto = 8888;
    String ip = "192.168.43.233";
    BufferedReader entrada;
    PrintStream salida;

    String genre;
    static String FRIEND_ADD = "";

    /**
     * Creates new form SingIn
     */
    public SingIn() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pop = new javax.swing.JCheckBox();
        electro = new javax.swing.JCheckBox();
        addFriend = new javax.swing.JButton();
        hiphop = new javax.swing.JCheckBox();
        reggae = new javax.swing.JCheckBox();
        rockroll = new javax.swing.JCheckBox();
        bachata = new javax.swing.JCheckBox();
        rap = new javax.swing.JCheckBox();
        trashmetal = new javax.swing.JCheckBox();
        balada = new javax.swing.JCheckBox();
        passWord = new javax.swing.JLabel();
        freind = new javax.swing.JLabel();
        banda = new javax.swing.JCheckBox();
        salsa = new javax.swing.JCheckBox();
        dance = new javax.swing.JCheckBox();
        jazz = new javax.swing.JCheckBox();
        ska = new javax.swing.JCheckBox();
        jTextField4 = new javax.swing.JTextField();
        punk = new javax.swing.JCheckBox();
        jTextField6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buttonCreate = new javax.swing.JButton();
        rock = new javax.swing.JCheckBox();
        userName = new javax.swing.JLabel();
        fullName = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        passWord1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setFocusable(false);

        pop.setBackground(new java.awt.Color(102, 102, 102));
        pop.setText("Pop");

        electro.setBackground(new java.awt.Color(102, 102, 102));
        electro.setText("Electroc");

        addFriend.setText("Add");
        addFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFriendActionPerformed(evt);
            }
        });

        hiphop.setBackground(new java.awt.Color(102, 102, 102));
        hiphop.setText("Hip-Hop");

        reggae.setBackground(new java.awt.Color(102, 102, 102));
        reggae.setText("Reggae");

        rockroll.setBackground(new java.awt.Color(102, 102, 102));
        rockroll.setText("Rock&Roll");

        bachata.setBackground(new java.awt.Color(102, 102, 102));
        bachata.setText("Bachata");

        rap.setBackground(new java.awt.Color(102, 102, 102));
        rap.setText("Rap");

        trashmetal.setBackground(new java.awt.Color(102, 102, 102));
        trashmetal.setText("Trash Metal");

        balada.setBackground(new java.awt.Color(102, 102, 102));
        balada.setText("Balada");

        passWord.setText("Password:");

        freind.setText("Friend:");

        banda.setBackground(new java.awt.Color(102, 102, 102));
        banda.setText("Banda");

        salsa.setBackground(new java.awt.Color(102, 102, 102));
        salsa.setText("Salsa");

        dance.setBackground(new java.awt.Color(102, 102, 102));
        dance.setText("Dance");

        jazz.setBackground(new java.awt.Color(102, 102, 102));
        jazz.setText("Jazz");

        ska.setBackground(new java.awt.Color(102, 102, 102));
        ska.setText("Ska");

        punk.setBackground(new java.awt.Color(102, 102, 102));
        punk.setText("Punk");

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/josek/Escritorio/imagenes/create-new-user-icon-3234.png")); // NOI18N

        buttonCreate.setText("Create");
        buttonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateActionPerformed(evt);
            }
        });

        rock.setBackground(new java.awt.Color(102, 102, 102));
        rock.setText("Rock");

        userName.setText("User Name: ");

        fullName.setText("Full Name:");

        age.setText("Age:");

        passWord1.setText("Genre: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passWord)
                    .addComponent(freind)
                    .addComponent(addFriend)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(age)
                    .addComponent(fullName)
                    .addComponent(userName)
                    .addComponent(passWord1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField1)
                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reggae)
                                    .addComponent(pop)))
                            .addComponent(rock)
                            .addComponent(hiphop)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rockroll)
                                    .addComponent(balada))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(banda)
                                    .addComponent(rap)))
                            .addComponent(buttonCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(electro)
                                    .addComponent(bachata))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ska)
                                    .addComponent(salsa)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(trashmetal)
                                        .addComponent(dance))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(punk)
                                        .addComponent(jazz))))))
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fullName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(age)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passWord1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rock)
                    .addComponent(pop)
                    .addComponent(electro)
                    .addComponent(salsa))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hiphop)
                    .addComponent(reggae)
                    .addComponent(bachata)
                    .addComponent(ska))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rockroll)
                    .addComponent(rap)
                    .addComponent(trashmetal)
                    .addComponent(jazz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balada)
                    .addComponent(banda)
                    .addComponent(dance)
                    .addComponent(punk))
                .addGap(18, 18, 18)
                .addComponent(passWord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(freind)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(addFriend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCreate))
                    .addComponent(jLabel1))
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 521, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateActionPerformed
        // TODO add your handling code here:
        
        try {
            SingInCliente = new Socket(ip, puerto);
            entrada = new BufferedReader(new InputStreamReader(SingInCliente.getInputStream()));
            salida = new PrintStream(SingInCliente.getOutputStream());
            System.out.println("Server Connected <SingIn>");

        } catch (IOException e) {
            System.out.println("Server Disconnected ");
        }
        
        String userName = this.jTextField1.getText();
        String fullName = this.jTextField2.getText();
        String ageUser = this.jTextField3.getText();
        String password = this.jTextField4.getText();
        String friend = this.jTextField6.getText();
        if (userName.trim().isEmpty() || fullName.trim().isEmpty() || ageUser.trim().isEmpty() || password.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Error: Empty Fields : ", "Sing In", 1);
        } else {
            genre = "";
            if (rock.isSelected()) {
                genre += "1 ";
            }
            if (hiphop.isSelected()) {
                genre += "2 ";
            }
            if (rockroll.isSelected()) {
                genre += "3 ";
            }
            if (balada.isSelected()) {
                genre += "4 ";
            }
            if (pop.isSelected()) {
                genre += "5 ";
            }
            if (reggae.isSelected()) {
                genre += "6 ";
            }
            if (rap.isSelected()) {
                genre += "7 ";
            }
            if (banda.isSelected()) {
                genre += "8 ";
            }
            if (electro.isSelected()) {
                genre += "9 ";
            }
            if (bachata.isSelected()) {
                genre += "10 ";
            }
            if (trashmetal.isSelected()) {
                genre += "11 ";
            }
            if (dance.isSelected()) {
                genre += "12 ";
            }
            if (salsa.isSelected()) {
                genre += "13 ";
            }
            if (ska.isSelected()) {
                genre += "14 ";
            }
            if (jazz.isSelected()) {
                genre += "15 ";
            }
            if (punk.isSelected()) {
                genre += "16 ";
            }
            String friends = FRIEND_ADD;

            JAXBObjectToXml xml = new JAXBObjectToXml();

            User user = new User();

            user.setUsername(userName);
            user.setName(fullName);
            user.setAge(ageUser);
            user.setLike(genre);
            user.setPass(password);

            user.setFriends(friends);

            user.setTag("GoSingIn");
            
            
            String xml_string = xml.ConvertToXML(user, User.class);

            System.out.println(">>> " + xml_string + "</--AddUser-->");

            User user2 = new User();
            user2 = xml.ConvertToUser(xml_string);

            // System.out.println(user2.getUsername());
            try {

                salida.println(xml_string);        //Envio información al servidor
                String msj = entrada.readLine();        //recibe datos del server

                System.out.println(":" + msj);

                if (msj.equals("SI")) {
                    
                    JOptionPane.showMessageDialog(this, "User Created _ Welcome to Odyssey", "Sing in", 3);
                }

            } catch (IOException e) {
                System.out.println("odyssey.Login.inicio() eRROR");
            }
        }

    }//GEN-LAST:event_buttonCreateActionPerformed

    private void addFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFriendActionPerformed
        
        try {
            SingInCliente = new Socket(ip, puerto);
            entrada = new BufferedReader(new InputStreamReader(SingInCliente.getInputStream()));
            salida = new PrintStream(SingInCliente.getOutputStream());
            System.out.println("Server Connected <SingIn>");

        } catch (IOException e) {
            System.out.println("Server Disconnected ");
        }
        
        String f = jTextField6.getText();

        User consulta = new User();
        JAXBObjectToXml xmlConsulta = new JAXBObjectToXml();
        // Enviar xml de consulta de amigo a agregar-....
        consulta.setFriends(f);

        String xml_string = xmlConsulta.ConvertToXML(consulta, User.class);

        System.out.println(">>> " + xml_string + "</--ConFrie-->");

        User resFrie = new User();
        resFrie = xmlConsulta.ConvertToUser(xml_string);

        
        /*
        if (servidor responde YES el amigo se agrega al string FRIEND_ADD + " " )
        else (Se envia un msj a la interface de que el usuario o el username no existe dentro de la base de datos)
              
        */
        

    }//GEN-LAST:event_addFriendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SingIn().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFriend;
    private javax.swing.JLabel age;
    private javax.swing.JCheckBox bachata;
    private javax.swing.JCheckBox balada;
    private javax.swing.JCheckBox banda;
    private javax.swing.JButton buttonCreate;
    private javax.swing.JCheckBox dance;
    private javax.swing.JCheckBox electro;
    private javax.swing.JLabel freind;
    private javax.swing.JLabel fullName;
    private javax.swing.JCheckBox hiphop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JCheckBox jazz;
    private javax.swing.JLabel passWord;
    private javax.swing.JLabel passWord1;
    private javax.swing.JCheckBox pop;
    private javax.swing.JCheckBox punk;
    private javax.swing.JCheckBox rap;
    private javax.swing.JCheckBox reggae;
    private javax.swing.JCheckBox rock;
    private javax.swing.JCheckBox rockroll;
    private javax.swing.JCheckBox salsa;
    private javax.swing.JCheckBox ska;
    private javax.swing.JCheckBox trashmetal;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
